### PR TITLE
Add `data-` attributeBindings to swiper-slide components

### PR DESCRIPTION
**Pull request by anulman**
I used all `data-` attributes mentioned in the [Swiper API docs](http://idangero.us/swiper/api/), plus `data-id` for more manual handling.

### CODE REVIEW

**Comment by Matt-Jensen** [comment]
Looking good, however I can't merge without tests 🙂

**Comment by anulman** [comment]
Sounds good! Something like the classlist tests in https://github.com/Ember-Swiper/ember-cli-swiper/blob/master/tests/integration/components/swiper-slide-test.js ?

**Comment by Matt-Jensen** [comment]
Yes please and thank you!

**Comment by anulman** [comment]
Tests added. Pardon the `eslint-disable-line`; I though the tradeoff was well worth DRYing up that test. If you'd rather we rm it, hoping you can suggest your preferred course of action :)

**Pull request closed without merging**
