### PR TITLE
Remove Usage of Prototype Extension Methods

### PR DESCRIPTION
**Pull request by topaxi**
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility

### CODE REVIEW

**Comment by Matt-Jensen** [comment]
Ember [extends the native array prototype](https://guides.emberjs.com/v2.17.0/configuring-ember/disabling-prototype-extensions) with [Ember.Array](https://emberjs.com/api/ember/2.17/classes/EmberArray), so I'm not currently concerned about older browsers, however I am concerned about Fastboot users that may not be able to rely on array extensions. @0xadada Any thoughts?

**Comment by topaxi** [comment]
It extends this by default, yes, but I disable native extensions in all my applications, I don't think an addon should rely on these to be present. If you want to use them, please add a note to the README that this addon will not work without native extensions.

In my humble opinion, as we are talking about one single function call, I think it would be worth to support the whole Ember ecosystem and not only those with enabled native extensions.

**Comment by topaxi** [comment]
I'd be happy to create a pull-request with [ember-disable-prototype-extensions](https://github.com/ember-cli/ember-disable-prototype-extensions).

**Comment by Matt-Jensen** [comment]
Great points all around.  To get the green from me I'd like to see [ember-disable-prototype-extensions](https://github.com/ember-cli/ember-disable-prototype-extensions) added to prove we are only talking about a single function call and lets update the PR title to something like "remove usage of prototype extensions".  Then I'm in.

**Comment by Matt-Jensen** [comment]
You're right.  Sorry had no idea that was already installed! This PR is about supporting older browsers after all. LGTM 👍

**Pull request merged**
